import { useEffect, useMemo, useState } from 'react';
import { apiFetch, API_BASE } from '../services/api';
import { useAuth } from '../context/AuthContext';
import { useDevice } from '../hooks_useDevice';

const currentYear = 2026;
function emptyPolicy() { return { id:null, label:'', division:'Saudi Division', nationality:'SAUDI', projectId:'', packageId:'', expectedHours:8, active:true }; }
function emptyCompensation() { return { employeeId:'', baseSalary:0, hourlyRate:0, overtimeMultiplier:1.5, housingAllowance:0, transportAllowance:0, otherAllowances:0 }; }
function emptyAdjustment(month=4, year=2026) { return { id:null, employeeId:'', month, year, type:'allowance', label:'', amount:0, note:'' }; }
export default function PayrollPage() {
  const { user } = useAuth(); const { isMobile } = useDevice();
  const [month, setMonth] = useState(4); const [year, setYear] = useState(currentYear);
  const [summary, setSummary] = useState(null); const [policies, setPolicies] = useState([]); const [projects, setProjects] = useState([]); const [packages, setPackages] = useState([]);
  const [employees, setEmployees] = useState([]); const [compensationItems, setCompensationItems] = useState([]); const [adjustments, setAdjustments] = useState([]);
  const [policyForm, setPolicyForm] = useState(emptyPolicy()); const [compForm, setCompForm] = useState(emptyCompensation()); const [adjustmentForm, setAdjustmentForm] = useState(emptyAdjustment(4, currentYear));
  const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const canManage = ['System Owner', 'HR Manager', 'HR'].includes(user?.role);
  useEffect(() => { loadAll(); }, [month, year]);
  async function loadAll() {
    try {
      setError('');
      const [summaryRes, projectsRes, usersRes, compRes, adjRes] = await Promise.all([
        apiFetch(`/payroll/summary?month=${month}&year=${year}`), apiFetch('/projects'), apiFetch('/users'), apiFetch('/payroll/compensation'), apiFetch(`/payroll/adjustments?month=${month}&year=${year}`)
      ]);
      setSummary(summaryRes.summary); setPolicies(summaryRes.workHourPolicies || []); setProjects(projectsRes.projects || []); setPackages(projectsRes.packages || []);
      setEmployees((usersRes.users || []).filter((x)=> x.role !== 'System Owner')); setCompensationItems(compRes.compensation || []); setAdjustments(adjRes.adjustments || []);
      setAdjustmentForm((prev)=> ({ ...prev, month, year }));
    } catch (err) { setError(err.message); }
  }
  const filteredPackages = useMemo(() => !policyForm.projectId ? packages : packages.filter((pkg) => pkg.projectId === Number(policyForm.projectId)), [packages, policyForm.projectId]);
  async function savePolicy(e){ e.preventDefault(); try { const payload={...policyForm, projectId: policyForm.projectId || null, packageId: policyForm.packageId || null, nationality: policyForm.division === 'Saudi Division' ? 'SAUDI' : 'NON-SAUDI'}; const res=await apiFetch('/payroll/policies',{method:'POST', body:JSON.stringify(payload)}); setPolicies(res.workHourPolicies||[]); setPolicyForm(emptyPolicy()); setMessage('Work hour policy saved successfully.'); loadAll(); } catch(err){ setError(err.message); } }
  async function saveCompensation(e){ e.preventDefault(); try { const res=await apiFetch('/payroll/compensation',{method:'POST', body:JSON.stringify(compForm)}); setCompensationItems(res.compensationItems||[]); setCompForm(emptyCompensation()); setMessage('Employee compensation saved.'); } catch(err){ setError(err.message); } }
  async function saveAdjustment(e){ e.preventDefault(); try { const payload={...adjustmentForm, month, year}; const res=await apiFetch('/payroll/adjustments',{method:'POST', body:JSON.stringify(payload)}); setAdjustments(res.adjustments||[]); setAdjustmentForm(emptyAdjustment(month,year)); setMessage('Payroll adjustment saved.'); loadAll(); } catch(err){ setError(err.message); } }
  async function deletePolicy(id){ try { const res=await apiFetch(`/payroll/policies/${id}`,{method:'DELETE'}); setPolicies(res.workHourPolicies||[]); setMessage('Work hour policy removed.'); } catch(err){ setError(err.message); } }
  async function deleteAdjustment(id){ try { await apiFetch(`/payroll/adjustments/${id}`,{method:'DELETE'}); setMessage('Adjustment removed.'); loadAll(); } catch(err){ setError(err.message); } }
  function startEdit(policy){ setPolicyForm({ id:policy.id, label:policy.label||'', division:policy.division||'Saudi Division', nationality:policy.nationality || (policy.division === 'Saudi Division' ? 'SAUDI' : 'NON-SAUDI'), projectId:policy.projectId||'', packageId:policy.packageId||'', expectedHours:policy.expectedHours||8, active:policy.active !== false }); }
  const exportUrl=`${API_BASE}/payroll/export?month=${month}&year=${year}`;
  return (<div className={isMobile ? 'mobile-page' : 'page'}>
    <section className="card"><div className="page-header"><div><h1>Payroll Phase 2</h1><p>Monthly payroll with compensation, allowances, deductions, advances, and payslip-ready runs.</p></div><div className="inline-actions wrap-actions"><select value={month} onChange={(e)=>setMonth(Number(e.target.value))}>{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{i+1}</option>)}</select><input value={year} onChange={(e)=>setYear(Number(e.target.value))} className="compact-input" /><a className="button-link" href={exportUrl}>Export Excel</a>{canManage ? <button onClick={async()=>{const res=await apiFetch('/payroll/run',{method:'POST', body:JSON.stringify({month,year})}); setMessage(`Payroll run #${res.run.id} created.`);}}>Create Payroll Run</button>:null}</div></div>{message ? <div className="alert success">{message}</div>:null}{error ? <div className="alert error">{error}</div>:null}
      <div className={isMobile ? 'mobile-stat-grid' : 'stat-grid'}>
        <article className="stat-card"><span>Employees</span><strong>{summary?.totals?.employees || 0}</strong><small>Scoped users only</small></article>
        <article className="stat-card"><span>Gross</span><strong>{summary?.totals?.grossAmount || 0}</strong><small>Before deductions</small></article>
        <article className="stat-card"><span>Deductions</span><strong>{summary?.totals?.deductionsAmount || 0}</strong><small>Absence + manual</small></article>
        <article className="stat-card"><span>Net</span><strong>{summary?.totals?.netAmount || 0}</strong><small>Payable amount</small></article>
      </div></section>
      <section className={isMobile ? 'card' : 'grid-two'}>
        <div className="card table-wrap"><div className="page-header compact"><div><h2>Work Hour Policies</h2><p>Saudi default 8 hours. Non-Saudi default 10 hours. You can override manually.</p></div></div><div className="policy-grid">{policies.map((policy)=><div key={policy.id} className="permission-box"><div className="page-header compact"><div><h3>{policy.label}</h3><p className="small muted">{policy.division} • {policy.expectedHours} hrs/day</p></div><div className="inline-actions">{canManage ? <button type="button" className="ghost" onClick={()=>startEdit(policy)}>Edit</button>:null}{canManage && user?.role==='System Owner' ? <button type="button" className="ghost danger-text" onClick={()=>deletePolicy(policy.id)}>Delete</button>:null}</div></div><div className="details-list small"><span>Project: <strong>{policy.projectId ? (projects.find((p)=>p.id===policy.projectId)?.name || policy.projectId) : 'All projects'}</strong></span><span>Package: <strong>{policy.packageId ? (packages.find((p)=>p.id===policy.packageId)?.name || policy.packageId) : 'All packages'}</strong></span><span>Status: <strong>{policy.active ? 'Active' : 'Inactive'}</strong></span></div></div>)}</div></div>
        {canManage ? <form className="card table-wrap" onSubmit={savePolicy}><div className="page-header compact"><div><h2>{policyForm.id ? 'Edit Policy' : 'Add Policy'}</h2><p>Create division defaults or project/package overrides.</p></div></div><div className="form-grid compact-form"><label>Label<input value={policyForm.label} onChange={(e)=>setPolicyForm((prev)=>({...prev,label:e.target.value}))} placeholder="Example: Zuluf Package A"/></label><label>Division<select value={policyForm.division} onChange={(e)=>setPolicyForm((prev)=>({...prev,division:e.target.value}))}><option>Saudi Division</option><option>Non-Saudi Division</option></select></label><label>Daily Hours<input type="number" min="1" step="0.5" value={policyForm.expectedHours} onChange={(e)=>setPolicyForm((prev)=>({...prev, expectedHours:Number(e.target.value)}))}/></label><label>Project<select value={policyForm.projectId} onChange={(e)=>setPolicyForm((prev)=>({...prev, projectId:e.target.value, packageId:''}))}><option value="">All Projects</option>{projects.map((project)=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label>Package<select value={policyForm.packageId} onChange={(e)=>setPolicyForm((prev)=>({...prev, packageId:e.target.value}))}><option value="">All Packages</option>{filteredPackages.map((pkg)=><option key={pkg.id} value={pkg.id}>{pkg.name}</option>)}</select></label><label className="checkbox-row span-2"><input type="checkbox" checked={policyForm.active} onChange={(e)=>setPolicyForm((prev)=>({...prev, active:e.target.checked}))}/>Active policy</label></div><div className="inline-actions wrap-actions"><button type="submit">Save Policy</button><button type="button" className="ghost" onClick={()=>setPolicyForm(emptyPolicy())}>Reset</button></div></form>:null}
      </section>
      <section className={isMobile ? 'card' : 'grid-two'}>
        <form className="card table-wrap" onSubmit={saveCompensation}><div className="page-header compact"><div><h2>Employee Compensation</h2><p>Base salary, hourly rate, overtime multiplier, and fixed allowances.</p></div></div><div className="form-grid compact-form"><label>Employee<select value={compForm.employeeId} onChange={(e)=>setCompForm((prev)=>({...prev, employeeId:e.target.value}))}><option value="">Select employee</option>{employees.map((employee)=><option key={employee.id} value={employee.employeeId || employee.id}>{employee.name} • {employee.gasId}</option>)}</select></label><label>Base Salary<input type="number" min="0" step="0.01" value={compForm.baseSalary} onChange={(e)=>setCompForm((prev)=>({...prev, baseSalary:Number(e.target.value)}))}/></label><label>Hourly Rate<input type="number" min="0" step="0.0001" value={compForm.hourlyRate} onChange={(e)=>setCompForm((prev)=>({...prev, hourlyRate:Number(e.target.value)}))}/></label><label>OT Multiplier<input type="number" min="1" step="0.1" value={compForm.overtimeMultiplier} onChange={(e)=>setCompForm((prev)=>({...prev, overtimeMultiplier:Number(e.target.value)}))}/></label><label>Housing Allowance<input type="number" min="0" step="0.01" value={compForm.housingAllowance} onChange={(e)=>setCompForm((prev)=>({...prev, housingAllowance:Number(e.target.value)}))}/></label><label>Transport Allowance<input type="number" min="0" step="0.01" value={compForm.transportAllowance} onChange={(e)=>setCompForm((prev)=>({...prev, transportAllowance:Number(e.target.value)}))}/></label><label className="span-2">Other Allowances<input type="number" min="0" step="0.01" value={compForm.otherAllowances} onChange={(e)=>setCompForm((prev)=>({...prev, otherAllowances:Number(e.target.value)}))}/></label></div><div className="inline-actions wrap-actions"><button type="submit">Save Compensation</button><button type="button" className="ghost" onClick={()=>setCompForm(emptyCompensation())}>Reset</button></div><div className="simple-list">{compensationItems.slice(0,8).map((item)=><div key={item.employeeId} className="request-card"><strong>Employee #{item.employeeId}</strong><div className="muted small">Base {item.baseSalary} • OT x{item.overtimeMultiplier}</div></div>)}</div></form>
        <form className="card table-wrap" onSubmit={saveAdjustment}><div className="page-header compact"><div><h2>Manual Adjustments</h2><p>Allowances, deductions, and advances for the selected month.</p></div></div><div className="form-grid compact-form"><label>Employee<select value={adjustmentForm.employeeId} onChange={(e)=>setAdjustmentForm((prev)=>({...prev, employeeId:e.target.value}))}><option value="">Select employee</option>{employees.map((employee)=><option key={employee.id} value={employee.employeeId || employee.id}>{employee.name} • {employee.gasId}</option>)}</select></label><label>Type<select value={adjustmentForm.type} onChange={(e)=>setAdjustmentForm((prev)=>({...prev, type:e.target.value}))}><option value="allowance">Allowance</option><option value="deduction">Deduction</option><option value="advance">Advance</option></select></label><label>Label<input value={adjustmentForm.label} onChange={(e)=>setAdjustmentForm((prev)=>({...prev, label:e.target.value}))} placeholder="Example: Food allowance"/></label><label>Amount<input type="number" step="0.01" value={adjustmentForm.amount} onChange={(e)=>setAdjustmentForm((prev)=>({...prev, amount:Number(e.target.value)}))}/></label><label className="span-2">Note<textarea value={adjustmentForm.note} onChange={(e)=>setAdjustmentForm((prev)=>({...prev, note:e.target.value}))} rows="2" /></label></div><div className="inline-actions wrap-actions"><button type="submit">Save Adjustment</button><button type="button" className="ghost" onClick={()=>setAdjustmentForm(emptyAdjustment(month,year))}>Reset</button></div><div className="simple-list">{adjustments.slice(0,8).map((item)=><div key={item.id} className="request-card"><div className="inline-actions"><strong>{item.label}</strong><button type="button" className="ghost danger-text" onClick={()=>deleteAdjustment(item.id)}>Delete</button></div><div className="muted small">{item.type} • {item.amount}</div></div>)}</div></form>
      </section>
      <section className="card table-wrap compact-table"><div className="page-header compact"><div><h2>Monthly Payroll Summary</h2><p>Now includes compensation, fixed allowances, manual adjustments, deductions, and net amount.</p></div></div><table><thead><tr><th>Name</th><th>GAS ID</th><th>Base</th><th>OT Pay</th><th>Allow.</th><th>Deductions</th><th>Net</th><th>Actions</th></tr></thead><tbody>{(summary?.rows || []).map((row)=><tr key={row.employeeId}><td><strong>{row.employeeName}</strong><div className="muted small">{row.projectName} • {row.packageName}</div></td><td>{row.gasId}</td><td>{row.basePay}</td><td>{row.overtimePay}</td><td>{Number((row.housingAllowance + row.transportAllowance + row.otherAllowances + row.allowanceAdjustments).toFixed(2))}</td><td>{row.deductionsAmount}</td><td><strong>{row.netAmount}</strong></td><td><span className="muted small">Run to generate payslip</span></td></tr>)}</tbody></table></section>
  </div>);
}
